### PR TITLE
Migrated log4js to latest version

### PR DESCRIPTION
**Pull request by privateOmega**

### CODE REVIEW

**Comment by privateOmega** [comment]
@Hugo-ter-Doest Could you please take a look at this PR, merge it and release a new build on npm ASAP? When I get time, I will update the code base to work with current Sentence Object in natural-node

**Comment by Hugo-ter-Doest** [comment]
Will do that tonight.

**Comment by Hugo-ter-Doest** [comment]
Thanks for your work! I saw that you made changes to the global configuration settings. This global config is not working correctly because it is still local to each module. I know that I have to create a module for settings and require that in each module in order to get something like global settings.

Thanks again for your help. Will bump the version now and upload to NPM.

**Comment by Hugo-ter-Doest** [comment]
done!

**Comment by privateOmega** [comment]
@Hugo-ter-Doest Thanks, I will try to contribute as much as possible to chart-parsers and natural node in the near future.

**Pull request merged**
